version: "3.8"

services:
  neo4j:
    build: ./neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/test1234"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
    volumes:
      - ./data:/data
    networks:
      - chatbot-network

  chatbot-web:
    build: .
    ports:
      - "8000:8000"
    environment:
      NEO4J_URI: "bolt://neo4j:7687"
      NEO4J_USERNAME: "neo4j"
      NEO4J_PASSWORD: "test1234"
    env_file:
      - .env
    depends_on:
      - neo4j
    networks:
      - chatbot-network
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./templates:/app/templates

networks:
  chatbot-network:
    driver: bridge
